### ISSUE TITLE
[question] Publishing a new version to npm with the GIT_SSL_CAINFO fixes

### ISSUE THREAD

**Issue by kittaakos** [desktop/dugite#122]
Could you please publish a new version with the fixes of #86 and #87 to npm?

As I see the most recent version (1.40) is from `2017-08-30T03:39:41.116Z`. A newer version could be an alpha, beta, or whichever fits better to your plans.

Thank you!

**Comment by shiftkey** [comment]
@kittaakos done! https://github.com/desktop/dugite/tree/v1.41.0
