### ISSUE TITLE
Include captures in parsed errors

### ISSUE THREAD

**Issue by joshaber** [desktop/dugite#124]
Some of our error regexes include captures, but they aren't actually passed up and out to consumers. We should do that, though it'll require some refactoring of errors.

**Comment by shiftkey** [comment]
Seems legit. Probably a breaking change to the API as `parseError` is only returning an enum currently:

```ts
public static parseError(stderr: string): GitError | null {
  // ...
}
```

**Comment by niik** [comment]
'tis nice to have dreams but these have gone stale
