### ISSUE TITLE
Embeded git's low performance

### ISSUE THREAD

**Issue by frankLife** [desktop/dugite#147]
Is there any plan to improve emebed git's excute performance especially on windows system ?
It runs too slowlier rather than the git version which installed locally.

**Comment by shiftkey** [comment]
@frankLife could you provide some example benchmarks of what you are testing? `dugite` and it's native package `dugite-native` both build upon Git for Windows, so I'm curious how much things can differ.

**Comment by frankLife** [comment]
I write a example to show the problem like this: 

```
const path = require('path')
const {GitProcess} = require('dugite')
const dir = path.join(__dirname, 'test/dugite')
const {spawn} = require('child_process')

console.time('embed git status')
GitProcess.exec(['status', '--porcelain', '-u'], dir).then(()=>{
  console.timeEnd('embed git status')
})

console.time('local git status')
let status_child = spawn('git', ['status', '--porcelain', '-u'] ,{
  cwd: dir
})

status_child.on('exit', ()=>{
  console.timeEnd('local git status')
})


console.time('embed git branch')
GitProcess.exec(['branch', '-vv'], dir).then(()=>{
  console.timeEnd('embed git branch')
})

console.time('local git branch')
let branch_child = spawn('git', ['branch', '-vv'] ,{
  cwd: dir
})

branch_child.on('exit', ()=>{
  console.timeEnd('local git branch')
})
```

the result 

```
local git status: 99.740ms
local git branch: 98.741ms
embed git status: 4472.102ms
embed git branch: 4552.192ms
```
 
yout can try this code and I find the portable version of official git from [download page](https://git-scm.com/download/win) 
also has this problem that it is much slower than local install version

Do you @shiftkey have eny idea ?

**Comment by shiftkey** [comment]
@frankLife thanks for the repro steps. I'd love to understand more about your setup, so I ran this up on a VM with 2 cores, 4GB RAM and Win10 `10.0.17025.1000` and got similar results:

```
$ node -v
v8.8.1

$ node index.js
local git status: 58.886ms
embed git status: 68.990ms
embed git branch: 45.059ms
local git branch: 43.689ms

$ node index.js
local git status: 51.689ms
embed git status: 60.307ms
embed git branch: 37.388ms
local git branch: 40.533ms

$ node index.js
local git status: 49.556ms
local git branch: 42.362ms
embed git status: 71.120ms
embed git branch: 48.736ms

$ node index.js
local git status: 51.675ms
embed git status: 73.111ms
local git branch: 45.559ms
embed git branch: 48.158ms

$ node index.js
local git status: 49.066ms
local git branch: 42.429ms
embed git status: 72.381ms
embed git branch: 48.945ms

$ node index.js
local git status: 51.479ms
local git branch: 43.050ms
embed git branch: 47.136ms
embed git status: 73.980ms
```

Under the hood `dugite` does use [`execFile`](https://nodejs.org/dist/latest-v8.x/docs/api/child_process.html#child_process_child_process_execfile_file_args_options_callback) rather than `spawn`. We have talked about introducing a `spawn`-based API based on our work on Desktop, but let's see what we can do to make the current APIs better for your setup.

**Comment by frankLife** [comment]
My computer works on Win7. May system's version cause the strange result ? Do you have tested this on Win7 system ever ?

**Comment by shiftkey** [comment]
@frankLife what version of Node are you using? I'm still not really sure how to recreate this issue on my end.

> Do you have tested this on Win7 system ever?

We support running GitHub Desktop on Windows 7 (Electron currently uses the Node 7 runtime, not 8) and I'm not aware of any specific issues reported there.

To confirm, I ran the test again in a Windows 7 VM with 2 CPUs and 1GB of RAM in Node 8.9.1:

<img width="1005" src="https://user-images.githubusercontent.com/359239/33001765-12480c1a-ce04-11e7-8c81-7b3702262401.png">

**Comment by frankLife** [comment]
I use a colleague‘s computer to test the case , the result :

```
Administrator@PC-20170305HZOV MINGW64 /d/test_git
$ node index.js
local git branch: 59.450ms
embed git status: 89.342ms
embed git branch: 74.675ms
local git status: 81.733ms

Administrator@PC-20170305HZOV MINGW64 /d/test_git
$ node index.js
local git branch: 51.461ms
embed git branch: 70.445ms
embed git status: 94.383ms
local git status: 83.703ms

Administrator@PC-20170305HZOV MINGW64 /d/test_git
$ node index.js
local git branch: 43.716ms
local git status: 61.257ms
embed git status: 99.402ms
embed git branch: 89.580ms

```

I  think it is the enviroment problem of my computer .

**Comment by shiftkey** [comment]
@frankLife let me know if you find anything interesting to help recreate the problem and I'll reopen this issue

**Comment by frankLife** [comment]
![](https://img.alicdn.com/tfs/TB1VuV0jC_I8KJjy0FoXXaFnVXa-753-445.png)

same problem on other computer.
This computer work well early, but after I worf for some time , it just slow down now. Is there reason can result in this problem?

**Comment by frankLife** [comment]
![image](https://user-images.githubusercontent.com/5081884/34257543-3fdfbde0-e695-11e7-81d0-83454010c704.png)

another windows computer.
I think we can do something to solve this problem ?

**Comment by shiftkey** [comment]
@frankLife I've opened #157 to dig deeper into this. It's not available in an NPM release yet, but you could help with testing and getting better details about what's happening with your setup versus mine by following these steps.

In the `dugite` source:

 - checkout `debug-mode-enabled` branch associated with the PR
 - run `npm` to ensure you have the right dependencies
 - run `npm run build` to transpile the new code to JS

Then, in your test project:

 - copy the new `build/lib` contents to overwrite `node_modules/dugite/build/lib`
 - `npm install --save debug` to ensure you have `debug` added

Then set the `DEBUG` environment variable to `DUGITE:*` and run `node index.js` to add some extra tracing. This is how it looks on my machine in a CMD prompt:

<img width="299" src="https://user-images.githubusercontent.com/359239/34346863-4ecf7cc2-ea4c-11e7-854d-c7699460db87.png">

I still suspect we'll find most of the time is spent inside `execFile`, and but let's confirm that before we dig deeper.

**Comment by frankLife** [comment]
sure . These days I am too busy. when I have a break, I will give more information

**Comment by shiftkey** [comment]
@frankLife something we haven't discussed in here is the presence of anti-virus software on the machine.

I had a discussion with someone in https://github.com/desktop/desktop/issues/3724 and we traced the slowness of GitHub Desktop to every Git operations taking 4-5 seconds - similar to what you're reporting. Disabling their anti-virus product temporarily made the problem go away, which suggested that the anti-virus wasn't configured correctly to work with Desktop.

Could you confirm if any anti-virus software is installed on the problem machine, and whether disabling it affects the execution times of the test suite?

**Comment by frankLife** [comment]
@shiftkey ok , I will confirm to report here today

**Comment by frankLife** [comment]
sadly , I call out it support team to check whether our firewall can be closed. They tell me that is forbidden. 
I will check deeply like using `DUGITE:*` environment variable soon after these super busy days. 🐛

**Comment by frankLife** [comment]
![](https://img.alicdn.com/tfs/TB1kDC1mlTH8KJjy0FiXXcRsXXa-734-380.png)

I almostly think the setting like firewall is the key because I use the private computer to check that it runs well

**Comment by shiftkey** [comment]
> I almostly think the setting like firewall is the key because I use the private computer to check that it runs well

I'm not sure if it's a firewall specifically (your test harness is only reliant on local Git data, and doesn't need to use the network) but I'd look into products which monitor processes for untrusted or malicious actions and see if they're misconfigured and monitoring this Git's usage (it doesn't live in `Program Files` so it might stand out to these tools).

**Comment by frankLife** [comment]
I appreciate it and I would support you by providing any help if you need to find out the problem

**Comment by shiftkey** [comment]
Without any more information to help debug this issue I'm going to have to close this out as I'm not sure how to proceed here.
