### ISSUE TITLE
Support FreeBSD

### ISSUE THREAD

**Issue by ararunprasad** [desktop/dugite#154]
Currently dugite supports only 3 platforms(Windows, Linux and OSX). Requesting to support FreeBSD as well. I will submit a pull request if you guys are ready to incorporate.

**Comment by shiftkey** [comment]
@ararunprasad thanks for the interest! `dugite` depends on the native packages we publish over in [`desktop/dugite-native`](https://github.com/desktop/dugite-native). If we can publish builds for that then enabling builds for `dugite` is easy to do.

For convenience and repeatability, the builds for `dugite-native` are generated from CI platforms (Travis for macOS and Linux, Windows is pre-compiled) - if there's a way to easily create FreeBSD builds of Git and can then publish artifacts to GitHub then I'm open to figuring out how to integrate it all.

**Comment by shiftkey** [comment]
@ararunprasad I've moved this up to `dugite-native` as that's where the hard work needs to happen: https://github.com/desktop/dugite-native/issues/82

Once that's in place, it's trivial to update these bindings. Please follow along with the upstream issue.
