### ISSUE TITLE
Repo cloning error dialogue

### ISSUE THREAD

**Issue by tierninho** [desktop/dugite#155]
Perhaps we can change the error dialogue to something more understandable to the layman? and do we need some validation on the url field? I entered some jiberish in the url field and got this:

<img width="974" alt="33733870-ff4b191a-db3f-11e7-92f5-92d63e12b50f" src="https://user-images.githubusercontent.com/14828183/33894821-c7dc69ca-df13-11e7-994e-5baa824078df.png">
<img width="448" alt="33733867-ff1ce9dc-db3f-11e7-948a-9baa8f16140e" src="https://user-images.githubusercontent.com/14828183/33894824-c805eff2-df13-11e7-890a-f8d8a1cb70e7.png">

1.0.11-beta0, mac

related to: https://github.com/desktop/desktop/issues/3539

**Comment by joshaber** [comment]
@tierninho Should this be opened on desktop/desktop? It doesn't seem dugite-specific.

**Comment by tierninho** [comment]
@joshaber see comment here: https://github.com/desktop/desktop/issues/3539#issuecomment-350957267

**Comment by joshaber** [comment]
Doh! Ignore me!

**Comment by shiftkey** [comment]
For reference this is what the current version (1.5.0) of the app emits:

<img width="435" src="https://user-images.githubusercontent.com/359239/48744530-f73e1000-ec3d-11e8-927d-df9ff42de71c.png">

Looks like some old `git lfs clone` cruft was making it confusing.

I've also added a new test to https://github.com/desktop/dugite/pull/241/commits/b905a0fb16d721870cd0c00e20ec63f18782fc30 which ensures we return the right error code for this error, then it'll be up to Desktop to refresh it's dialog to make things a bit friendlier.
