### ISSUE TITLE
Compile embedded git with USE_LIBPCRE

### ISSUE THREAD

**Issue by ovy** [desktop/dugite#160]
I use a commit hook that does `git grep -P`, i.e. uses Perl regexps which is a compile time dependency. This works everywhere but Atom's git support, where it fails because that git is built without it.

It seems that just about everyone else compiles with pcre.  Short list of git versions we use where this works:
* Linux and Homebrew distributions
* Github Desktop on Mac and Windows
* Recent Apple versions (Apple Git-98). The system (xcode) git used to not have PCRE a while back (when it was an ancient 1.8.something) but it does as of High Sierra.
* Official git-scm.org package for Mac

Having an embedded git, while convenient, should follow mainstream git as closely as possible in my opinion. And PCRE in turn is probably the "mainstream RE" these days and not some esoteric option.

I've taken to telling people who use Atom to simply remove the dugite git-core, forcing it to use system, but this seems sub-optimal if you guys are relying on the behaviors of a fixed version.  Eliminating the grep -P is non-trivial.

**Comment by shiftkey** [comment]
@ovy can you re-file this over on https://github.com/desktop/dugite-native which is the actual Git toolchain? This behaviour is due to compiling Git with `NO_PERL` enable to avoid the dependency, and we can talk more about that over there.

**Comment by ovy** [comment]
Thanks @shiftkey -- opened https://github.com/desktop/dugite-native/issues/74 .
