### ISSUE TITLE
[question] Unexpected `stdout` when running `git check-ignore`

### ISSUE THREAD

**Issue by kittaakos** [desktop/dugite#178]
I tried to run `git check-ignore` from `dugite`. Unfortunately, I got different results when I ran it from a terminal, and when I executed the command from code. Perhaps, I misunderstood something, or I must be blind. Could you please tell me what is wrong with my test case? Thank you!

From the code:
```typescript
  describe('check-ignore', () => {
    it('should list the ignored files form the root', async () => {
      const testRepoPath = await initialize('check-ignore')

      const aFile = path.join(testRepoPath, 'a.txt')
      fs.writeFileSync(aFile, 'foo')
      expect(fs.readFileSync(aFile, { encoding: 'utf8' })).to.be.equal('foo')

      const gitignore = path.join(testRepoPath, '.gitignore')
      fs.writeFileSync(gitignore, 'a.txt')
      expect(fs.readFileSync(gitignore, { encoding: 'utf8' })).to.be.equal('a.txt')

      const result = await GitProcess.exec(['check-ignore', '*'], testRepoPath)

      verify(result, r => {
        expect(r.stdout.trim()).to.be.equal('a.txt')
      })
    })
  })
```
```
       check-ignore
         should list the ignored files form the root:

      AssertionError: expected '' to equal 'a.txt'
      + expected - actual

      +a.txt

      at helpers_1.verify.r (test/fast/git-process-test.ts:126:39)
      at Object.verify (test/helpers.ts:19:5)
      at Object.<anonymous> (test/fast/git-process-test.ts:125:7)
      at Generator.next (<anonymous>)
      at fulfilled (test/fast/git-process-test.ts:4:58)
      at <anonymous>
```

From a terminal:
```
mkdir tmp-check-ignore \
&& cd tmp-check-ignore \
&& git init -q \
&& echo "foo" > a.txt \
&& echo "a.txt" > .gitignore \
&& git check-ignore *
```
```
a.txt
```

**Comment by shiftkey** [comment]
@kittaakos I haven't had a chance to look into this, but a first step might be to check if `stderr` contains your expected message, rather than `stdout`?

**Comment by kittaakos** [comment]
I have checked both `stdin` and `stdout`; they're empty strings. I did some further investigation, and it seems, `git check-ignore` works correctly if I do not use the `*` as an argument. Here is a short example what I meant:

```typescript
  describe('check-ignore', () => {
    it('should list the ignored files from the root', async () => {
      const testRepoPath = await initialize('check-ignore')

      const aFile = Path.join(testRepoPath, 'a.txt')
      Fs.writeFileSync(aFile, 'foo')
      expect(Fs.readFileSync(aFile, { encoding: 'utf8' })).to.be.equal('foo')

      const bFile = Path.join(testRepoPath, 'a.txt')
      Fs.writeFileSync(bFile, 'bar')
      expect(Fs.readFileSync(bFile, { encoding: 'utf8' })).to.be.equal('bar')

      const gitignore = Path.join(testRepoPath, '.gitignore')
      Fs.writeFileSync(gitignore, 'a.txt')
      expect(Fs.readFileSync(gitignore, { encoding: 'utf8' })).to.be.equal('a.txt')

      const aResult = await GitProcess.exec(['check-ignore', 'a.txt'], testRepoPath)
      verify(aResult, r => {
        expect(r.exitCode).to.be.equal(0)
        expect(r.stdout.trim()).to.be.equal('a.txt')
      })

      const bResult = await GitProcess.exec(['check-ignore', 'b.txt'], testRepoPath)
      verify(bResult, r => {
        expect(r.exitCode).to.be.equal(1)
        expect(r.stdout.trim()).to.be.equal('')
      })
    })
  })
```

And the result is the same from a terminal:
```
mkdir tmp-check-ignore \
&& cd tmp-check-ignore \
&& git init -q \
&& echo "foo" > a.txt \
&& echo "bar" > b.txt \
&& echo "a.txt" > .gitignore \
&& git check-ignore a.txt \
&& git check-ignore b.txt
```
```
a.txt
```

**Comment by shiftkey** [comment]
@kittaakos I think this is because NodeJS might not be expanding `*` when it's an argument in the `child_process` APIs, unlike how a shell might do this.

[This question](https://stackoverflow.com/questions/11717281/wildcards-in-child-process-spawn) delves into a couple of the alternatives to this, but I don't think they'll work directly for this use case.

**Comment by kittaakos** [comment]
I found the exact same thread and tried out to call `git check-ignore *` with that way (`spawnSync `); it worked.
(Please note, the snippet assumes you have `git` on your path.)

```
describe('check-ignore', () => {
    it('should list the ignored files from the root', async () => {
      const testRepoPath = await initialize('check-ignore')

      const aFile = Path.join(testRepoPath, 'a.txt')
      Fs.writeFileSync(aFile, 'foo')
      expect(Fs.readFileSync(aFile, { encoding: 'utf8' })).to.be.equal('foo')

      const bFile = Path.join(testRepoPath, 'a.txt')
      Fs.writeFileSync(bFile, 'bar')
      expect(Fs.readFileSync(bFile, { encoding: 'utf8' })).to.be.equal('bar')

      const gitignore = Path.join(testRepoPath, '.gitignore')
      Fs.writeFileSync(gitignore, 'a.txt')
      expect(Fs.readFileSync(gitignore, { encoding: 'utf8' })).to.be.equal('a.txt')

      const cp = require('child_process')
      let child
      const cmd = 'git check-ignore *'
      const cwd = testRepoPath

      if ('win32' === process.platform) {
        child = cp.spawnSync('cmd.exe', ['/s', '/c', '"' + cmd + '"'], {
          cwd,
          windowsVerbatimArguments: true
        })
      } else {
        child = cp.spawnSync('/bin/sh', ['-c', cmd], { cwd })
      }
      expect(child.stdout.toString().trim()).to.be.equal('a.txt')
    })
  })
```

**Comment by kittaakos** [comment]
If I change the `exec` implementation from `execFile` to `spawn`, it works.
```typescript
// ...
const command = [gitLocation, ...args].join(' ')
let cp: ChildProcess
if ('win32' === process.platform) {
  cp = spawn('cmd.exe', ['/s', '/c', '"' + command + '"'], spawnOptions)
} else {
  cp = spawn('/bin/sh', ['-c', command], spawnOptions)
}

// ...
cp.on('error', ...)
cp.on('exit', ...)
cp.stdout.on('data', ...)
cp.stderr.on('data', ...)
```
(Just wanted to try it out.)

Also, all tests pass except the `throws error when exceeding the output range`. The `maxBuffer` seems to be ignored, and the test passes instead of the expected error. I am not yet positive, but `spawn` might not have the 200 * 1024 byte limitation like `execFile` has.

Although `maxBuffer` is declared on the `SpawnSyncOptionsWithStringEncoding` in the typings, it is not mentioned in the [documentation](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options) and does not seem to be used in the [code](https://github.com/nodejs/node/blob/254058109f469f64b8ca23bb65a206abab380604/lib/child_process.js#L521) either.

I also found [this](http://www.hacksparrow.com/difference-between-spawn-and-exec-of-node-js-child_process.html) and [this](https://github.com/nodejs/node/issues/4236) threads on the `spawn` `maxBuffer` topic.

By the way, alternatively, I could use the `git clean -ndX` instead of `git check-ignore *`.

**Comment by kittaakos** [comment]
@shiftkey, are there any plans adjusting the implementation. I could take care of the PR if you do not have time.

Also, I could understand if you do not want to switch from `cp.execFile` to `cp.spawn` but then, could we expose the error handler code into the API so that I could wrap `spawn` and call `git-process#spawn` instead of `git-process#exec`. Thanks!

**Comment by shiftkey** [comment]
> are there any plans adjusting the implementation. I could take care of the PR if you do not have time.

I'm swamped, but would be happy to review the changes if you've found a way to resolve it.

**Comment by kittaakos** [comment]
Great, I will take care of it. Thanks!

**Comment by kittaakos** [comment]
@shiftkey, here is a work-in-progress PR with my changes: https://github.com/desktop/dugite/pull/181

**Comment by niik** [comment]
Seems we dropped the ball here but what this is really about is whether or not to invoke Git using a shell or not. That's what the proposed PR is doing and that's something we definitely don't want as it opens us up to a world of hurt when it comes to escaping arguments (the rules of which differ wildly between platforms). In order to do something like this with dugite today please use something like `glob` to get an explicit list of files and pass those as individual arguments.
