### ISSUE TITLE
Add test to ensure `sslCAInfo` is unset for Windows

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/dugite#190]
Let's make sure future releases of dugite has `sslCAInfo` unset.

The change to unset this config property was done in #189.

**Comment by shiftkey** [comment]
@iAmWillShepherd I think this will be handled once Git for Windows 2.18.1 lands and `http.schannelUseSSLCAInfo` will be applied in our system Git config.

```
# Git for Windows 2.18.1 will support controlling how curl uses any certificate
# bundle - rather than just loading the bundle if http.useSSLCAInfo is set
# For the moment we want to favour using the OS certificate store unless the
# user has overriden this in their global configuration.
#
# details: https://github.com/dscho/git/blob/6152657e1a97c478df97d633c47469043b397519/Documentation/config.txt#L2135
git config --file $SYSTEM_CONFIG http.schannelUseSSLCAInfo "false"
```

If we need to do any other system config checks or verification, those should occur in `dugite-native` when we're setting up the system config.

Let me know if I've missed any other context on this.
