### ISSUE TITLE
logo contribution

### ISSUE THREAD

**Issue by reallinfo** [desktop/dugite#192]
Hello, I want to I want to contribute to dugide and i want to deisgn a logo. What do you think? 

I will waiting feedback. 

Good work.

**Comment by reallinfo** [comment]
Hey @shiftkey I designed a logo. What do you think?

![dugite](https://user-images.githubusercontent.com/36298335/43204416-667a4ec8-9029-11e8-8ed9-47daae648df7.jpg)

**Comment by niik** [comment]
Hey @reallinfo, thank you so much for wanting to contribute and on behalf of the team behind dugite I apologize for the lack of feedback to your submission. The logo looks great, that said we're not looking to promote this library in such a way that it would necessitate a logo. The primary mission of this library is to support GitHub Desktop. With that I'm going to close this issue but again, thanks for your contribution and sorry we never said so at the time you submitted it!
