### ISSUE TITLE
Issue using dugite with electron and webpack

### ISSUE THREAD

**Issue by joecorkerton** [desktop/dugite#196]
I am trying to test out dugite with a fresh electron project and I'm having problems getting it running. I'm using webpack to bundle the js, which is producing the following errors:

`Module not found: Error: Can't resolve 'child_process' in '../node_modules/dugite/build/lib'`
`Module not found: Error: Can't resolve 'fs' in '../node_modules/dugite/build/lib'`

I tried setting the LOCAL_GIT_DIRECTORY environment variable but that did not resolve the issue.

Any suggestions to get it working?

**Comment by kittaakos** [comment]
If you have this issue when creating the `bundle.js`, you could try to work around it by mocking [`node`](https://webpack.js.org/configuration/node/) in your `webpack.config.js`:
```
module.exports = {
  // ...
  node: {
    fs: 'empty',
    child_process: 'empty'
    // ...
  }
  // ...
};
```

**Comment by shiftkey** [comment]
@joecorkerton are you able to share an example webpack config for how you're doing the bundling? We do this with Desktop, but it'd be nice to have an agnostic demo project to help with troubleshooting, as this seems different to what we uncovered with bundling in #96.

**Comment by joecorkerton** [comment]
@shiftkey I've created a new repo with the minimum setup required to produce the error. It can be found here https://github.com/joecorkerton/dugite-test

**Comment by joecorkerton** [comment]
@kittaakos I can do that and I no longer get an error while bundling, but then dugite no longer works:

`Error: Git not supported on platform: undefined`

**Comment by kittaakos** [comment]
I got the very same result. I am positive, it is possible to use `dugite` in electron. I give it another try ...

**Comment by kittaakos** [comment]
I have created a PR against your setup: https://github.com/joecorkerton/dugite-test/pull/1
I am able to call `dugite`, but it results in an error:

```
Uncaught (in promise) Error: Git could not be found at the expected path: '/git/bin/git'. This might be a problem with how the application is packaged, so confirm this folder hasn't been removed when packaging.
    at bundle.js:1
    at exithandler (child_process.js:294)
    at ChildProcess.errorhandler (child_process.js:306)
    at emitOne (events.js:116)
    at ChildProcess.emit (events.js:211)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:196)
    at onErrorNT (internal/child_process.js:372)
    at _combinedTickCallback (internal/process/next_tick.js:138)
    at process._tickCallback (internal/process/next_tick.js:180)
```

I could take another look tomorrow. There must be something with the bundling process.

By the way, you can also check out this dugite-electron boilerplate: https://github.com/kittaakos/electron-boilerplate

**Comment by kittaakos** [comment]
If I hack the `git` path (in debug mode), then it works.

![screen shot 2018-06-13 at 17 47 28](https://user-images.githubusercontent.com/1405703/41362582-060bd6a0-6f32-11e8-96ce-2e5be533dfe4.jpg)

**Comment by joecorkerton** [comment]
@kittaakos I have gotten a bit further now. If I set the target in the webpack.config to `electron-renderer` then the issue about not finding fs and child_process is gone (it no longer needs to be stubbed in the config as you suggested).

However now I also get the same issue with the git path (`git/bin/git`). Will look into this further as it seems to be

**Comment by joecorkerton** [comment]
I still don't fully understand the issue, but when I create a new electron app with https://github.com/electron-userland/electron-webpack-quick-start it seems to work, so I will go with that for now.

Thanks for you help
