### ISSUE TITLE
Atom IDE prevents commits due to PREFIX being set if managing node versions with NVM

### ISSUE THREAD

**Issue by GrayedFox** [desktop/dugite#198]
Hi there,

No idea why this is happening but I can no longer make commits via the Git pane interface inside the Atom IDE editor.

I now always get this error: 
![screenshot from 2018-07-09 21-42-39](https://user-images.githubusercontent.com/6493307/42472352-4758ffc2-83c1-11e8-9604-ba3bea9fad20.png)

It is only when using the Atom IDE editor - my PREFIX is blank (as it is by default) inside of my terminal session, and thus I have no problem.

**Comment by shiftkey** [comment]
@GrayedFox which OS?

**Comment by shiftkey** [comment]
My psyhic debugger thinks it's related to this

https://github.com/desktop/dugite/blob/a6a9ad14576188e0cd6da4d895fe817224ee0d14/lib/git-environment.ts#L114-L118

Could there be a situation where `git` runs a commit hook which is running `nvm` inside Atom?

**Comment by GrayedFox** [comment]
Ubuntu 18.04

**Comment by GrayedFox** [comment]
> Could there be a situation where git runs a commit hook which is running nvm inside Atom?

That's exactly what is happening - the pre-commit is running some linter (`lint-staged`) - I'm trying to contribute to VuePress so it's not my project to change really :dancer:

**Comment by GrayedFox** [comment]
Is it possible to resolve things using `env.DUGITEPREFIX` instead?

**Comment by shiftkey** [comment]
`PREFIX` is a [Git environment variable](https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables) and not something we control (aside from unsetting the environment variable, which will affect our Git usage):

> `PREFIX` is similar, but for the system-wide configuration. Git looks for this file at `$PREFIX/etc/gitconfig`.

**Comment by shiftkey** [comment]
You might be able to workaround the issue by doing `unset PREFIX` before you invoke `nvm` but it's hard to say without looking at an example of the script.

**Comment by GrayedFox** [comment]
I can also just use my terminal for this project when committing etc - it's not a huge loss - but I would ask why Dugite needs to change/update the Git env variable and especially only on Linux? Or perhaps a more straight forward technical question -- does removing this conditional actually break things on Linux? 

Reading the entry in the Git docs, it states that `PREFIX` is similar [to the home var] but is used "...for the system-wide configuration.". Is it appropriate, then, for a 3rd party application to Git to set what looks to be an option reserved for users who want change their Git preferences? 

I might be thoroughly missing the point - apologies if this is the case!

**Comment by shiftkey** [comment]
>  Is it appropriate, then, for a 3rd party Git based application to set what looks to be an environment variable meant for users who want change their own Git preferences?

System git configuration values are a way for Git installations to configure themselves without modifying a user's global configuration. 

The order of precedence in how these configs are applied is:

 - system config
 - global config
 - local/repo config

Global overrides system, local overrides global. So this is intended to avoid interfering with your existing setup - it's just that the `PREFIX` environment variable that Git uses clashes with the `PREFIX` environment variable that `nvm` uses.

> does removing this conditional actually break things on Linux?

I had a look at our latest installation and I don't see an `/etc/gitconfig` bundled, but I have https://github.com/desktop/dugite-native/pull/73 open which requires shipping a system configuration for all platforms, so I will be relying on this soon.

**Comment by GrayedFox** [comment]
Fair enough,

Thank you for your time and energy put into explaining and handling this in
a transparent manner :) I think you can consider this closed as a non
dugite issue - it seems like, in this case, it's probably best if the user
works around this edge case of getting nvm and Atom/deugite to work
together where a subshell is spawned for a pre-commit hook.

Best

Che

m: +49 176 4566 3935
e: che.fisher@gmail.com
KeyBase <https://keybase.io/grayedfox> - GitHub
<https://github.com/grayedfox> - Twitter <https://twitter.com/GrayedFox>

**Comment by shiftkey** [comment]
@GrayedFox no problem, and best of luck with it!

**Comment by GrayedFox** [comment]
Hmm, just figured out something strange about this error which popped up again, thought I'd post here in case people find it. It seems like if markdownlint fails (which I think depends on this) while a pre-commit hook is running in a sub shell (say, a sub shell spawned by Atom when you use the Git tab), it doesn't stop cleanly, and results in the PREFIX env var being left as the one defined for dugite.

Fixing the linting errors, in my case, removed the error entirely. Not sure where this error originates from (markdown or node for example) but good to know that the error is transient and, in my case, based on markdownlint failing.
