### ISSUE TITLE
better error message for "account disabled" response from server

### ISSUE THREAD

**Issue by shiftkey** [desktop/dugite#264]
From https://github.com/desktop/desktop/issues/6538#issuecomment-452350468

```
Cloning into '/Users/***/***/***'...
remote: Your account is disabled. Please see https://github.com/account/billing
fatal: unable to access 'https://github.com/***/***.git/': The requested URL returned error: 403
```

**Comment by zerefwayne** [comment]
Hi @shiftkey, is this project under active development? I would love to contribute to this.

**Comment by shiftkey** [comment]
@zerefwayne go for it!

**Comment by shiftkey** [comment]
@zerefwayne check out one of our previous PRs that add new error codes, e.g. #105

**Comment by niik** [comment]
This has not been a problem for a few years so I'm gonna close this
