### ISSUE TITLE
standardize on using yarn and yarn lockfile

### ISSUE THREAD

**Issue by shiftkey** [desktop/dugite#277]
The other projects in this organization use `yarn`, and this is currently the only exception:

 - [ ] import a vendored `yarn` and add the related `.yarnrc` config
 - [ ] regenerate the lockfile
 - [ ] remove any `package.json` scripts that might use `npm` directly
 - [ ] test a release using `yarn` and update documentation

**Comment by j-f1** [comment]
What do you think about making a desktop/scripts repo that has the vendored yarn (plus other common deps like TS), and include it as a submodule in all repos?

**Comment by shiftkey** [comment]
It's something that interests me, but for the moment I'd like to follow [the rule of 3](https://en.wikipedia.org/wiki/Rule_of_three_(computer_programming)) to identify what's actually needed in this hypothetical situation.
