### ISSUE TITLE
[Discovery] Verify if the new stash implementation in Git 2.22.0 uses the same error messages as found in Git for Windows

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/dugite#356]
The latest stashing feature that will be shipped in the [upcoming version of Desktop](https://github.com/desktop/desktop/pull/7656) was implemented in a less than optimal because we we're unable to parse stash error messages the way we've done for every other message. This is due to the fact that Windows and macOS/Linux use differing implementations of Git.

Both macOS and Linux both use the _real_ version of Git, https://github.com/git/git, while Windows uses a fork of `git/git`, https://github.com/git-for-windows/git. This distinction became an issue for stashing because stashing as implemented **before** `Git 2.22.0` differed from the Git for Windows version of Git in one key way: it was implemented as a shell script and therefore has different runtime mechanics and error messages. These differences made it very difficult and maybe even impossible to follow `Dugite` current pattern of implementing error parsing.

Here's one instance of the error messages differing slightly: `git stash apply`
* `git/git` - [source](https://github.com/git/git/blob/8104ec994ea3849a968b4667d072fedd1e688642/git-stash.sh#L612)
* `git-for-windows/git` - [source](https://github.com/git-for-windows/git/blob/7c229f3e9df5ff20d0c0bd7086792fffe3954718/builtin/stash.c#L434)

While the message in this one instance is only slightly different, it's important to point out that some of the commands ran in the shell script to check the index or to build a diff also emit their output to `stdout` resulting in an error message that includes messages that aren't specific to stashing.

Here's a concrete example of what I mean:

**macOS & Linux - `git/git`**

Stash some changes.
```sh
(b1*) » git stash       iamwill@artemis
Saved working directory and index state WIP on b1: 963a4bd 2
```

Move `master` ahead of `b1`
```sh
(b1) » git checkout master
Switched to branch 'master'

(master) » echo 'test' > modified

(master*) » git commit -am "move ahead"
[master 090c9a3] move ahead
 1 file changed, 1 insertion(+), 5 deletions(-)
```

Produce stash conflicts by popping stash made on `b1`
```sh
git stash pop
Auto-merging modified
CONFLICT (content): Merge conflict in modified
```

Produce error by stashing files in _stash_ conflicted state
```sh
» git stash   iamwill@artemis
modified: needs merge
modified: needs merge
modified: unmerged (a3b69a1dc23386eb0d9f71f5e4593b29242e248a)
modified: unmerged (9daeafb9864cf43055ae93beb0afd6c7d144bfa4)
modified: unmerged (a9573cfe4236922ede629bb5e06212cc048bb100)
fatal: git-write-tree: error building trees
Cannot save the current index state 
```

**Windows - `git-for-windows/git`**

Stash some changes
```sh
(b1) $ git stash
warning: LF will be replaced by CRLF in README.md.
The file will have its original line endings in your working directory
Saved working directory and index state WIP on b1: 075ab1e initial commit
```

Move `master` ahead of `b1`
```sh
(b1) $ git checkout master
Switched to branch 'master'

(master) $ echo "Move ahead of b1" >> README.md

(master) $ git commit -am "move ahead"
warning: LF will be replaced by CRLF in README.md.
The file will have its original line endings in your working directory
[master e9a5e55] move ahead
 1 file changed, 1 insertion(+)
```

Produce stash conflicts by popping stash made on `b1`
```sh
(master) $ git stash pop
Auto-merging README.md
CONFLICT (content): Merge conflict in README.md
The stash entry is kept in case you need it again.
```

Produce error by stashing files in _stash_ conflicted state
```sh
(master) - $ git stash
README.md: needs merge
```

As you can see, doing the same actions results in different output. Relying on the error code is also not much use since the shell script reuses the same error code for multiple errors within stashing and within the different scripts used in `git-stash.sh`.

Now that the `git-stash` implementation has been rewritten in c in `Git 2.22.0`, I think it's worth doing a bit of digging to see if the two implementations are the same, at least as far as error messages are concerned. I do not think we need to worry about mechanics any longer since both implementations are written using the same language and should get executed the same. Once it's verified that the implementations for `git-stash` are the same, I think we should upgrade `Dugite` to target the upcoming `git/git`, which is currently at `v2.22.0-rc2`, and `git-for-windows/git`, which is currently at `v2.22.0-rc2.windows.1`.

**Comment by niik** [comment]
We've not seen this be an issue so I'm going to close this out
