### ISSUE TITLE
GitLFS does not handle GIT_TERMINAL_PROMPT env

### ISSUE THREAD

**Issue by chasse20** [desktop/dugite#385]
Because **git-lfs.exe** (64bit) is spawned as a child process of **git.exe**, it appears to be incapable of inheriting the ENV variables that are passed into the exec function. This leads to zombie background processes/memory leaks for handling applications such as Github Desktop when you need to perform commands like `git lfs locks` asking for user authentication for HTTP repos. Github Desktop uses the `GIT_TERMINAL_PROMPT=0` environment variable hack to avoid this for vanilla Git. It functions properly if authentication is provided.

A simple, albeit not the most efficient, solution is to perform an `args.includes('lfs')` check and have it handled differently.

**Comment by chasse20** [comment]
Actually, this might not even be in Dugite's wheelhouse. GIT_TERMINAL_PROMPT isn't respected at all. I'm implementing a bit of LFS functionality for Github Desktop to eventually bring it to par with Perforce.

My hack solution that I can think of now (aside from assuming people have credentials setup), is going to involve using the stdin from the spawner to force fail any login prompt.

**Comment by niik** [comment]
Yeah, I'm afraid you're right that this is not in scope for dugite. Dugite sets the environment variables given to it with a few modifications and exceptions (see https://github.com/desktop/dugite/blob/main/lib/git-environment.ts#L78-L144). We don't do anything funky with GIT_TERMINAL_PROMPT. I'm going to close this.
