### ISSUE TITLE
Any way of stopping Dugite from downloading Git?

### ISSUE THREAD

**Issue by cab404** [desktop/dugite#462]
Hello! I am one of numerous NixOS maintainers, and am currently packaging one of numerous Dugite users.
Is there a way to disable downloading of Dugite's binaries with an environment variable?
Such flags exist for Electron and Playwright 
```
PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1
ELECTRON_SKIP_BROWSER_DOWNLOAD=1
``` 

That would be super nice to have 
```
DUGITE_SKIP_BIN_DOWNLOAD=1
```
...since those binaries won't work on Nix anyway :sweat_smile:

**Comment by niik** [comment]
Hey, @cab404, sorry for the late response. As you've probably realized alreay there's no such flag. I don't see why we wouldn't review a PR to add one but I'm curious about this

> ...since those binaries won't work on Nix anyway 😅

Dugite does ship with linux-compatible binaries and should download the correct ones, are you seeing something else in your testing?

**Comment by cab404** [comment]
> Dugite does ship with linux-compatible binaries
Those binaries are not statically linked, and that’s something NixOS doesn't work with out of the box — it provides it's own peculiar linking mechanics, so it should either be statically linked, linked in Nix, or patched)

**Comment by niik** [comment]
Closing in favor of https://github.com/desktop/dugite/issues/182 which appears to be very similar to this.
