### ISSUE TITLE
How to run git command interactively?

### ISSUE THREAD

**Issue by TerryChan** [desktop/dugite#502]
For some git commands, it maybe interactive, such as  git pull, when the file that pulled is opened locally, it will require user input. Such as the Word document is opened locally, and we pull it, it will prompt as below, and waiting user input(y or n).
`Unlink of file '新建 Microsoft Word 文档.docx' failed. Should I try again? (y/n)`
![image](https://user-images.githubusercontent.com/5396286/201062602-f1974883-dffd-4bec-8027-9553f1e613d9.png)

I want to achieve the same effect as the command line with dugite - stop to waiting the user input, and accept the input then continue. But I didn't find a method to implement it. Does anyone know how to make it with dugite:
1. How to let it stop when the git command asks user input?
2. How to pass user input to it and then it continues?

Thanks anyway

**Comment by niik** [comment]
dugite is intended to be used in as a library and as such it won't run Git commands interactively (we set TERM=dumb and we don't create a tty).

For this particular case it would appear you could use the GIT_ASK_YESNO environment variable to give it a custom executable which could handle the prompting for you.

https://github.com/git-for-windows/git/blob/85dac07b93425aba69537d42ef036aa8413ae37c/compat/mingw.c#L221-L227

This is however all out of scope for dugite so I'm going to close this.
