### ISSUE TITLE
'subtree' is not a git command

### ISSUE THREAD

**Issue by raphaeltm** [desktop/dugite#505]
I'm working on a tool that depends on subtrees. It looks like the git that is bundled with Dugite doesn't include the subtree command. I've made it work using the instructions [here](https://github.com/desktop/dugite/blob/main/docs/environment-variables.md) but I think it would make sense to have git-subtree bundled with Dugite.

**Comment by niik** [comment]
Hey @raphaeltm, I'm glad to hear you were able to find a workaround. Dugite's main objective is to support GitHub Desktop which does not make use of git-subtree. Should git-subtree be adopted by Git and made into a core part of the Git project it would be included but until such a time we're not going to add it as a dependency of Dugite so I'm closing this.
