### ISSUE TITLE
rmSync is not defined

### ISSUE THREAD

**Issue by jyzhang11** [desktop/dugite#523]
rmSync is called in script/download-git.js , but not imported

**Comment by maifeeulasad** [comment]
Okay, I guess this can be resolved here, in this very specific like: https://github.com/desktop/dugite/blob/e602d0ccaa5e364d6768543921046bd85ed7382a/script/download-git.js#L7

**Comment by niik** [comment]
Fixed in https://github.com/desktop/dugite/pull/538
