### ISSUE TITLE
Drop `electron` from repository tags

### ISSUE THREAD

**Issue by LeoDog896** [desktop/dugite#552]
![image](https://github.com/desktop/dugite/assets/26509014/95413396-d8b4-4e05-b7f0-69afe8f2c0d3)

Most likely carried from the desktop/desktop repository, when `dugite` has no electron bindings at all.

**Comment by linonetwo** [comment]
It can be easily used in electron, like https://github.com/tiddly-gittly/TidGi-Desktop

**Comment by LeoDog896** [comment]
> It can be easily used in electron, like https://github.com/tiddly-gittly/TidGi-Desktop

That doesn't seem like a good reason to keep the tag - the same can be said for [Tauri](https://tauri.app/).

**Comment by linonetwo** [comment]
I think dugite is build with electron usage in mind, because they build it is for use it in https://github.com/desktop/desktop/
