### ISSUE TITLE
Request: Publish version 2.5.2 to the npm package registry

### ISSUE THREAD

**Issue by DeeDeeG** [desktop/dugite#554]
I notice there is a version **2.5.2** here: https://github.com/desktop/dugite/releases

But the latest version published to npm package registry is **2.5.1** at the time I'm writing this: https://www.npmjs.com/package/dugite?activeTab=versions

Whenever maintainers here get the chance, could we get v2.5.2 published to the npm package registry? Thanks for considering.

Related:
- https://github.com/desktop/dugite/pull/549

**Comment by DeeDeeG** [comment]
Sorry to bother, but I thought I would try again during the work week.

@sergiou87 any chance this version of dugite can be published to the npm registry?

**Comment by sergiou87** [comment]
I think it should be all good now. It still doesn't show up in npmjs but I got the email saying 2.5.2 was successfully released, so it might be a caching issue.
